/*
 * This source file was generated by the Gradle 'init' task
 */
package org.os.simulator;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class OSApplicationTest {
    @Test
    void contextLoads() {
        // Simple test to verify Spring Boot context loads successfully
    }
}
